### ISSUE TITLE
Question about convert vertical to horizontal image 

### ISSUE THREAD

**Issue by phamkhactu** [haruishi43/equilib#18]
Thanks for great repo.

As the [link](https://github.com/FoxelSA/libgnomonic/wiki/Equirectangular%20mapping%20transformation) overview and the question from [stackoverflow](https://stackoverflow.com/questions/35232292/transform-and-remap-an-equirectangular-image-with-a-90-roll)
I have same case, with my image , your module support to make 90-roll(horizontal)

Here is my image:
![test_supper](https://github.com/haruishi43/equilib/assets/42369268/27e2f86b-e117-493a-8a72-ab7514160af0)

Here is my expected:
![image](https://github.com/haruishi43/equilib/assets/42369268/38c6c6fe-d4a6-40dd-8a9e-2ba44adfb4c5)

Thank you

**Comment by haruishi43** [comment]
@phamkhactu did you try `equi2equi` with `rots`?

**Comment by phamkhactu** [comment]
> @phamkhactu did you try `equi2equi` with `rots`?

I don't know about `rots`. Could you explain it more detail?

**Comment by haruishi43** [comment]
```python
equi2equi = Equi2Equi(mode="bilinear")
rot = {"roll": 0, "pitch": np.pi/2, "yaw": 0}
out_img = equi2equi(src=src_img, rots=rot)
```

I tried your image, but just turning 90 degrees does not make the expected image (this may be due to the camera positioning).

![output_equi2equi_numpy_image](https://github.com/haruishi43/equilib/assets/7902640/e749a40c-85b1-48c7-acba-47c82fc43930)

See [Coordinate System](https://github.com/haruishi43/equilib#coordinate-system) for the definition of roll, pitch and yaw. You can also try out `equi2equi` using the script provided inside `scripts/equi2equi_numpy.py`.

**Comment by phamkhactu** [comment]
> ```python
> equi2equi = Equi2Equi(mode="bilinear")
> rot = {"roll": 0, "pitch": np.pi/2, "yaw": 0}
> out_img = equi2equi(src=src_img, rots=rot)
> ```
> 
> I tried your image, but just turning 90 degrees does not make the expected image (this may be due to the camera positioning).
> 
> ![output_equi2equi_numpy_image](https://user-images.githubusercontent.com/7902640/279851480-e749a40c-85b1-48c7-acba-47c82fc43930.jpg)
> 
> See [Coordinate System](https://github.com/haruishi43/equilib#coordinate-system) for the definition of roll, pitch and yaw. You can also try out `equi2equi` using the script provided inside `scripts/equi2equi_numpy.py`.

Many thanks!
