### ISSUE TITLE
The equi2equi function is used several times, but the result is the same

### ISSUE THREAD

**Issue by liangchengbeibian** [haruishi43/equilib#3]
I want to rotate a  equirectangular image and then turn it back to the original angle, so I use the equi2equi function twice, but the result is both the first choice. I also try to save the first result, reread the image and select again, but the result is the same。What should I do？

**Comment by haruishi43** [comment]
I'm trying to understand what you did. You rotated the image (call it A) and it becomes A'. And then you revert it back to the original angle (rotate by the inverse angle I presume?) and the image becomes A''. Are you trying to make sure that A == A''? If so, I'm pretty sure that it will be A =/= A'' since the image will be interpolated using bilinear interpolation when you rotate the image.
